rgname                 = "stage-rashmika-rg"
service_principal_name = "stage-rashmika-spn"
keyvault_name          = "stage-rashmika-kv-101"
SUB_ID = ""
node_pool_name = "stagenp"
cluster_name = "stage-rashmika-cluster"
