trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - azure-pipeline

stages:
- stage: validate
  displayName: "Validation Stage"

  jobs:
  - job: tf_validate
    displayName: "Terraform Validate Job"


    pool:
      name: agentpool_1
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
          backendAzureRmUseEntraIdForAuthentication: false
          backendServiceArm: 'Rashmika Subscription – MPN(08d552c6-56bb-47f3-ab48-de814729e62e)'
          backendAzureRmResourceGroupName: 'terraform-state-rg'
          backendAzureRmStorageAccountName: 'tfdevbackend2026rash'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'dev.tfstate'
          backendAzureRmAccessKey: '$(DEV_STORAGE_ACCOUNT_KEY)'
          
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
      
- stage: Dev_Deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs: 
  - job: terraform_apply_dev
    pool:
      name: agentpool_1
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Rashmika Subscription – MPN(08d552c6-56bb-47f3-ab48-de814729e62e)'
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfdevbackend2026rash'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
        backendAzureRmAccessKey: '$(DEV_STORAGE_ACCOUNT_KEY)'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Rashmika Subscription – MPN(08d552c6-56bb-47f3-ab48-de814729e62e)'
    
- stage: stage_deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs: 
  - job: terraform_apply_stage
    pool:
      name: agentpool_1
    steps: 

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/staging'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Rashmika Subscription – MPN(08d552c6-56bb-47f3-ab48-de814729e62e)'
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfstagebackend2026rash'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'stage.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/staging'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Rashmika Subscription – MPN(08d552c6-56bb-47f3-ab48-de814729e62e)'

