rgname                 = "dev-rashmika-rg"
service_principal_name = "dev-rashmika-spn"
keyvault_name          = "dev-rashmika-kv-101"
SUB_ID = ""
cluster_name = "dev-rashmika-cluster"
node_pool_name = "devnp"
